sudo: required
dist: trusty
language: node_js

node_js:
  - '10'
  - '12'

branches:
  only:
    - master
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)$/
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)-dev$/
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install:
  - npm ci
  - cp .env.example .env

before_script:
  - npm run check-package
  - npm run lint
  - docker build . -t dapi-dev
  - echo SERVICE_IMAGE_DAPI=dapi-dev >> .env
  - echo SERVICE_IMAGE_MACHINE=dashpay/js-machine:0.3.0-dev.3 >> .env
  - echo SERVICE_IMAGE_DRIVE=dashpay/drive:0.7.0-dev.2 >> .env

deploy:
  skip_cleanup: true
  provider: script
  script: bash bin/deploy.sh
  on:
    repo: dashevo/dapi
    tags: true
