os: linux
language: node_js
branches:
  only:
    - master
node_js:
  - '8'
install:
  - pip install awscli --upgrade --user
  - cd ..
  - git clone --depth=50 git@github.com:dashevo/mn-bootstrap.git mn-bootstrap
  - cd mn-bootstrap
  - . ./.env
  - $(~/.local/bin/aws ecr get-login --no-include-email)
  - cd ../dapi
  - npm install
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzmq3-dev
before_script:
  - npm run lint
deploy:
  skip_cleanup: true
  provider: script
  script: /bin/bash deploy.sh
  on:
    repo: dashevo/dapi
    branch: master
