sudo: required
dist: focal
language: node_js

node_js:
  - '12'

branches:
  only:
    - master
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)-dev$/
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

services:
  - docker

addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
    packages:
      - docker-ce
      - jq

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - if [[ -n $SDK_BRANCH ]]; then export SDK_INSTALL=github:dashevo/DashJS#$SDK_BRANCH; fi
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "Docker version:"
  - docker -v

install:
  - npm ci
  - cp .env.example .env
  # Get the latest version of travis-ci-tools
  - curl -s https://api.github.com/repos/dashevo/travis-ci-tools/releases/latest | jq -r '.tarball_url' | xargs -I {} -n1 wget -O travis-ci-tools.tar.gz -q {}
  - mkdir ~/travis-ci-tools && tar -C ~/travis-ci-tools -xvf travis-ci-tools.tar.gz
  - export CI_TOOLS_DIR="$(ls ~/travis-ci-tools)"
  - cd ~/travis-ci-tools/$CI_TOOLS_DIR
  - npm ci && npm link
  - if [[ -n $SDK_BRANCH ]]; then npm i github:dashevo/DashJS#$SDK_BRANCH ;fi

before_script:
  - print-bells
  - if [[ -z $SKIP_TEST_SUITE ]]; then source ./bin/start-local-node.sh $TRAVIS_BUILD_DIR/package.json --override-major-version=0 --dapi-branch=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --drive-branch=$DRIVE_BRANCH; fi
  - cd $TRAVIS_BUILD_DIR

script: >
  npm run check-package &&
  npm run lint &&
  npm run test:coverage &&
  if [[ -z $SKIP_TEST_SUITE ]]; then docker run --network="host" dashpay/platform-test-suite:$CURRENT_VERSION 127.0.0.1:3000 -s=platform -k=$FAUCET_PRIVATE_KEY -n=regtest --dpns-tld-identity-private-key=$DPNS_TOP_LEVEL_IDENTITY_PRIVATE_KEY --dpns-tld-identity-id=$DPNS_TOP_LEVEL_IDENTITY_ID --dpns-contract-id=$DPNS_CONTRACT_ID --npm-install=$SDK_INSTALL; fi

deploy:
  skip_cleanup: true
  provider: script
  script: bash bin/deploy.sh
  on:
    repo: dashevo/dapi
    tags: true
