os: linux
language: node_js
node_js:
  - '8'
install:
  - npm install
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzmq3-dev
before_script:
  - npm run lint
