os: linux
language: node_js
branches:
  only:
    - master
node_js:
  - '8'
install:
  - npm install
before_script:
  - npm run lint
deploy:
  skip_cleanup: true
  provider: script
  script: /bin/bash deploy.sh
  on:
    repo: dashevo/dapi
    branch: master
