name: release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["tests"]
    branches:
      - master
      - v[0-9]+.[0-9]+-dev
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    types: 
      - completed

jobs:
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-20.04
    steps:
    - name: Check package version matches tag
      uses: geritol/match-tag-to-package-version@0.0.2
      env:
        TAG_PREFIX: refs/tags/v
    - name: Pull Docker layer cache
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        restore-keys: |
          docker-layer-caching-tests-
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: strophy/drive
        tag_with_ref: true
